[package]
name = "aoc_2024_rust"
version = "0.1.0"
edition = "2021"
default-run = "aoc_2024_rust"

[dependencies]
itertools = "0.13.0"
reqwest = { version = "0.12", features = ["json","cookies"] }
tailcall = "1.0.1"
tokio = { version = "1", features = ["full"] }
